spring.application.name=ecommerce
spring.datasource.url=jdbc:mysql://caboose.proxy.rlwy.net:27190/railway
spring.datasource.username=root
spring.datasource.password=jawQbCBIIQZxEUCNrYGcKZzmXjBIsEPo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
jwt.secret=irfan-ecommerce-secret-key-must-be-at-least-32-characters-long
server.error.include-message=always
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG